import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { HiAcademicCap, HiBookOpen, HiClipboardCheck, HiCog, HiPrinter, HiShieldCheck } from 'react-icons/hi';
import { useAuth } from '../context/AuthContext';
import * as api from '../services/libretasService';

const NOTAS = ['', 'AD', 'A', 'B', 'C'];
const tabsAdmin = [
  ['registro', 'Registro de notas', HiBookOpen], ['config', 'Cursos y responsables', HiCog],
  ['periodos', 'Bimestres', HiClipboardCheck], ['merito', 'Orden de mérito', HiAcademicCap],
  ['auditoria', 'Auditoría', HiShieldCheck],
];

const errorText = e => e.response?.data?.error || 'No se pudo completar la operación';

function imprimirLibreta(data) {
  const { alumno, notas, conducta, observaciones } = data;
  const cursos = [...new Map(notas.map(n => [`${n.area}|${n.curso}`, { area: n.area, curso: n.curso }])).values()];
  const celda = (arr, nombre, p, campo = 'curso') => arr.find(x => x[campo] === nombre && Number(x.numero) === p)?.calificacion || '';
  const comentario = p => observaciones.find(x => x.tipo === 'COMENTARIO_TUTOR' && Number(x.numero) === p)?.texto || observaciones.find(x => x.tipo === 'COMENTARIO_DOCENTE' && Number(x.numero) === p)?.texto || '';
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Libreta - ${alumno.nombre_completo}</title><style>
  @page{size:A4 landscape;margin:7mm}*{box-sizing:border-box}body{margin:0;color:#4b1515;font-family:Arial;background:#fffaf2}.page{width:100%;min-height:190mm;border:3px double #9b1c25;padding:12mm;page-break-after:always;background:linear-gradient(135deg,#fffdf8,#fff8eb)}h1,h2{font-family:Georgia;color:#7d1018}.cover{display:grid;grid-template-columns:1fr 1fr;gap:15mm}.brand{text-align:center;border:1px solid #c9973e;border-radius:18px;padding:12mm}.brand h1{font-size:42px;margin:10px}.badge{background:#850f18;color:white;padding:10px 30px;border-radius:22px;font-size:26px;font-weight:bold}.student{margin-top:28px;text-align:left;border:2px solid #d4a14a;border-radius:14px;padding:18px;font-size:18px;line-height:2}.quote{font-family:Georgia;font-style:italic}.legend{display:grid;gap:7px;margin-top:20px}.legend div{padding:8px;border-left:12px solid #a71d2a;background:#fff}.title{font-size:27px;border-bottom:2px solid #c9973e;padding-bottom:8px}table{width:100%;border-collapse:collapse;background:#fffdf8}th{background:#8d1520;color:white}th,td{border:1px solid #d6b77e;padding:7px;text-align:center}td:nth-child(1),td:nth-child(2){text-align:left}.inside{display:grid;grid-template-columns:2fr 1fr;gap:12px}.comments{display:grid;gap:10px}.comment{border:1px solid #d6b77e;border-radius:12px;padding:12px;min-height:65px;background:white}.footer{text-align:center;margin-top:14px;font-family:Georgia}@media print{button{display:none}.page:last-child{page-break-after:auto}}</style></head><body>
  <section class="page cover"><div><h2 class="title">SITUACIÓN AL FINALIZAR EL AÑO LECTIVO</h2><p>Inicial: culminación del año escolar</p><div class="legend"><div><b>AD — Logro destacado</b><br>Supera lo esperado para la competencia.</div><div><b>A — Logro esperado</b><br>Alcanza satisfactoriamente lo programado.</div><div><b>B — En proceso</b><br>Requiere acompañamiento para lograrlo.</div><div><b>C — En inicio</b><br>Necesita mayor tiempo y apoyo docente.</div></div></div><div class="brand"><p class="quote">“La tradición es un reto para la educación”</p><h2>Colegio</h2><h1>Harvard</h1><p>INICIAL – PRIMARIA – SECUNDARIA</p><div class="badge">LIBRETA DE NOTAS</div><div class="student"><b>ALUMNO:</b> ${alumno.nombre_completo}<br><b>CÓDIGO:</b> ${alumno.codigo_alumno}<br><b>GRADO:</b> ${alumno.grado} &nbsp; <b>SECCIÓN:</b> ${alumno.seccion}<br><b>NIVEL:</b> ${alumno.nivel} &nbsp; <b>AÑO:</b> ${alumno.anio}<br><b>TELÉFONO:</b> ${alumno.celular || ''}</div><p class="quote">“Enseña al niño el camino en que debe andar”</p><p><b>Tutor(a):</b> ${alumno.tutor || ''}</p></div></section>
  <section class="page"><h2 class="title">DISTRIBUCIÓN DE ÁREAS Y CURSOS — ${alumno.nombre_completo}</h2><div class="inside"><div><table><thead><tr><th>ÁREA</th><th>CURSO</th><th>I</th><th>II</th><th>III</th><th>IV</th></tr></thead><tbody>${cursos.map(c => `<tr><td>${c.area}</td><td>${c.curso}</td>${[1,2,3,4].map(p=>`<td>${celda(notas,c.curso,p)}</td>`).join('')}</tr>`).join('')}</tbody></table><h2>Conducta y hábitos</h2><table><thead><tr><th>CONCEPTO</th><th>I</th><th>II</th><th>III</th><th>IV</th></tr></thead><tbody>${[...new Set(conducta.map(c=>c.nombre))].map(n=>`<tr><td>${n}</td>${[1,2,3,4].map(p=>`<td>${celda(conducta,n,p,'nombre')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div><h2>COMENTARIO DEL PROFESOR</h2><div class="comments">${[1,2,3,4].map(p=>`<div class="comment"><b>${p}.</b> ${comentario(p)}</div>`).join('')}</div></div></div><p class="footer">Colegio Harvard — UGEL 06</p></section><script>window.onload=()=>window.print()</script></body></html>`;
  const w = window.open('', '_blank', 'noopener,noreferrer');
  if (!w) return toast.error('Permita las ventanas emergentes para imprimir');
  w.document.write(html); w.document.close();
}

export default function Libretas() {
  const { usuario } = useAuth();
  const admin = usuario?.rol_codigo === 'SUPER_ADMIN';
  const [data, setData] = useState(null); const [tab, setTab] = useState('registro'); const [busy, setBusy] = useState(true);
  const [asigId, setAsigId] = useState(''); const [periodoId, setPeriodoId] = useState(''); const [gradebook, setGradebook] = useState(null);
  const [notas, setNotas] = useState({}); const [motivo, setMotivo] = useState(''); const [comentarios, setComentarios] = useState({});
  const [area, setArea] = useState(''); const [curso, setCurso] = useState({ nombre:'', id_area:'' }); const [asignacion, setAsignacion] = useState({ id_aula:'', id_curso:'', id_docente:'' });
  const [merito, setMerito] = useState([]); const [audit, setAudit] = useState([]); const [acom, setAcom] = useState({ alumno:'', conducta:{}, tutor:'', padre:'' });
  const recargar = async () => { setBusy(true); try { const r=await api.cargarLibretas(); setData(r.data.data); if(!asigId&&r.data.data.asignaciones[0]) setAsigId(String(r.data.data.asignaciones[0].id)); if(!periodoId&&r.data.data.periodos[0]) setPeriodoId(String(r.data.data.periodos[0].id)); } catch(e){toast.error(errorText(e));} finally{setBusy(false);} };
  useEffect(()=>{recargar();},[]);
  const seleccion = useMemo(()=>data?.asignaciones.find(a=>String(a.id)===String(asigId)),[data,asigId]);
  const periodo = data?.periodos.find(p=>String(p.id)===String(periodoId));
  const cargar = async()=>{if(!asigId||!periodoId)return;try{const r=await api.cargarNotas({id_asignacion:asigId,id_periodo:periodoId});setGradebook(r.data.data);setNotas(Object.fromEntries(r.data.data.alumnos.map(a=>[a.id,a.calificacion||''])));}catch(e){toast.error(errorText(e));}};
  useEffect(()=>{if(asigId&&periodoId)cargar();},[asigId,periodoId]);
  const saveNotas=async()=>{try{await api.guardarNotas({id_asignacion:Number(asigId),id_periodo:Number(periodoId),motivo,notas:Object.entries(notas).filter(([,v])=>v).map(([id,v])=>({id_alumno:Number(id),calificacion:v}))});toast.success('Notas guardadas');setMotivo('');cargar();}catch(e){toast.error(errorText(e));}};
  const saveComment=async alumno=>{if(!comentarios[alumno])return;try{await api.guardarComentarioDocente({id_asignacion:Number(asigId),id_periodo:Number(periodoId),id_alumno:alumno,id_catalogo:Number(comentarios[alumno])});toast.success('Comentario guardado');}catch(e){toast.error(errorText(e));}};
  const tabs = admin ? tabsAdmin : [['registro','Mis cursos y notas',HiBookOpen], ...(usuario?.rol_codigo==='TUTOR'?[['acom','Conducta y tutoría',HiClipboardCheck]]:[])];
  if(busy&&!data)return <div className="p-8">Cargando módulo académico...</div>;
  const commentsDoc=data?.catalogo.filter(x=>x.tipo==='COMENTARIO_DOCENTE')||[], commentsTutor=data?.catalogo.filter(x=>x.tipo==='COMENTARIO_TUTOR')||[], notesParent=data?.catalogo.filter(x=>x.tipo==='NOTA_PADRE')||[];
  return <div className="p-4 md:p-7 space-y-5"><div className="bg-white border border-cream-200 rounded-2xl p-5 shadow-sm"><h1 className="text-2xl text-primary-800">Libretas y evaluación académica</h1><p className="text-sm text-cream-600 mt-1">Año escolar {data?.anio.anio} · Calificación AD, A, B y C</p></div>
    <div className="flex gap-2 overflow-x-auto">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2 rounded-xl whitespace-nowrap flex items-center gap-2 ${tab===id?'bg-primary-700 text-white':'bg-white border border-cream-200 text-primary-700'}`}><Icon/>{label}</button>)}</div>
    {tab==='registro'&&<section className="bg-white rounded-2xl border border-cream-200 p-5 space-y-4"><div className="grid md:grid-cols-2 gap-3"><label className="text-sm">Curso y aula<select className="input-field mt-1" value={asigId} onChange={e=>setAsigId(e.target.value)}>{data?.asignaciones.map(a=><option key={a.id} value={a.id}>{a.curso} · {a.grado} {a.seccion}{admin?` · ${a.docente}`:''}</option>)}</select></label><label className="text-sm">Bimestre<select className="input-field mt-1" value={periodoId} onChange={e=>setPeriodoId(e.target.value)}>{data?.periodos.map(p=><option key={p.id} value={p.id}>{p.nombre} · {p.estado}</option>)}</select></label></div>{!data?.asignaciones.length&&<p className="p-5 bg-amber-50 rounded-xl">Aún no tiene cursos asignados. El Superadministrador debe realizar la asignación.</p>}{gradebook&&<><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="bg-primary-700 text-white"><th className="p-3 text-left">Código</th><th className="p-3 text-left">Alumno</th><th className="p-3">Nota</th><th className="p-3 text-left">Comentario propio</th><th></th>{admin&&<th>Libreta</th>}</tr></thead><tbody>{gradebook.alumnos.map(a=><tr key={a.id} className="border-b border-cream-100"><td className="p-3">{a.codigo_alumno}</td><td className="p-3 font-medium">{a.nombre_completo}</td><td className="p-3"><select className="input-field min-w-20" value={notas[a.id]||''} onChange={e=>setNotas({...notas,[a.id]:e.target.value})}>{NOTAS.map(n=><option key={n} value={n}>{n||'—'}</option>)}</select></td><td className="p-3"><select className="input-field min-w-64" value={comentarios[a.id]||''} onChange={e=>setComentarios({...comentarios,[a.id]:e.target.value})}><option value="">Seleccione una opción</option>{commentsDoc.map(c=><option key={c.id} value={c.id}>{c.texto}</option>)}</select></td><td><button className="btn-gold" onClick={()=>saveComment(a.id)}>Guardar</button></td>{admin&&<td><button className="btn-primary flex gap-1" onClick={async()=>{try{const r=await api.cargarLibreta(a.id);imprimirLibreta(r.data.data);}catch(e){toast.error(errorText(e));}}}><HiPrinter/> Imprimir</button></td>}</tr>)}</tbody></table></div>{admin&&<input className="input-field" placeholder="Motivo obligatorio si modifica una nota existente" value={motivo} onChange={e=>setMotivo(e.target.value)}/>}<div className="flex justify-end"><button disabled={!admin&&periodo?.estado!=='ABIERTO'} className="btn-primary" onClick={saveNotas}>Guardar notas</button></div></>}</section>}
    {tab==='config'&&admin&&<section className="grid lg:grid-cols-3 gap-4"><div className="bg-white p-5 rounded-2xl border"><h2 className="text-lg">Nueva área</h2><input className="input-field my-3" value={area} onChange={e=>setArea(e.target.value)} placeholder="Nombre del área"/><button className="btn-primary" onClick={async()=>{try{await api.crearArea({nombre:area});setArea('');recargar();toast.success('Área guardada');}catch(e){toast.error(errorText(e));}}}>Guardar</button></div><div className="bg-white p-5 rounded-2xl border"><h2 className="text-lg">Nuevo curso</h2><select className="input-field mt-3" value={curso.id_area} onChange={e=>setCurso({...curso,id_area:e.target.value})}><option value="">Área</option>{data?.areas.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><input className="input-field my-3" value={curso.nombre} onChange={e=>setCurso({...curso,nombre:e.target.value})} placeholder="Curso"/><button className="btn-primary" onClick={async()=>{try{await api.crearCurso(curso);setCurso({nombre:'',id_area:''});recargar();toast.success('Curso guardado');}catch(e){toast.error(errorText(e));}}}>Guardar</button></div><div className="bg-white p-5 rounded-2xl border"><h2 className="text-lg">Asignar responsable</h2><select className="input-field mt-3" value={asignacion.id_aula} onChange={e=>setAsignacion({...asignacion,id_aula:e.target.value})}><option value="">Aula</option>{data?.aulas.map(x=><option key={x.id} value={x.id}>{x.nivel} · {x.grado} {x.seccion}</option>)}</select><select className="input-field mt-3" value={asignacion.id_curso} onChange={e=>setAsignacion({...asignacion,id_curso:e.target.value})}><option value="">Curso</option>{data?.cursos.map(x=><option key={x.id} value={x.id}>{x.area} · {x.nombre}</option>)}</select><select className="input-field my-3" value={asignacion.id_docente} onChange={e=>setAsignacion({...asignacion,id_docente:e.target.value})}><option value="">Docente</option>{data?.docentes.map(x=><option key={x.id} value={x.id}>{x.nombres} · {x.rol}</option>)}</select><button className="btn-primary" onClick={async()=>{try{await api.asignarCurso(asignacion);recargar();toast.success('Responsable asignado');}catch(e){toast.error(errorText(e));}}}>Asignar</button></div></section>}
    {tab==='periodos'&&admin&&<section className="grid md:grid-cols-4 gap-4">{data?.periodos.map(p=><div key={p.id} className="bg-white p-5 rounded-2xl border"><h2>{p.nombre}</h2><p className="my-3 text-sm">Estado: <b>{p.estado}</b></p><select className="input-field" value={p.estado} onChange={async e=>{try{await api.cambiarPeriodo(p.id,e.target.value);recargar();toast.success('Bimestre actualizado');}catch(err){toast.error(errorText(err));}}}><option>ABIERTO</option><option>REVISION</option><option>CERRADO</option></select></div>)}</section>}
    {tab==='merito'&&admin&&<section className="bg-white p-5 rounded-2xl border"><div className="flex gap-3 mb-4"><button className="btn-primary" disabled={!seleccion} onClick={async()=>{try{const r=await api.cargarMerito({id_aula:seleccion.id_aula,id_periodo:periodoId||undefined});setMerito(r.data.data);}catch(e){toast.error(errorText(e));}}}>Calcular bimestre</button><button className="btn-gold" disabled={!seleccion} onClick={async()=>{const r=await api.cargarMerito({id_aula:seleccion.id_aula});setMerito(r.data.data);}}>Calcular anual</button></div>{merito.map(x=><div className="grid grid-cols-[70px_1fr_100px] border-b p-3" key={x.id}><b>#{x.posicion}</b><span>{x.codigo_alumno} · {x.nombre_completo}</span><b>{x.puntaje.toFixed(2)}</b></div>)}</section>}
    {tab==='auditoria'&&admin&&<section className="bg-white p-5 rounded-2xl border"><button className="btn-primary mb-4" onClick={async()=>{const r=await api.cargarAuditoriaNotas();setAudit(r.data.data);}}>Cargar historial</button><div className="space-y-2">{audit.map(x=><div key={x.id} className="p-3 border rounded-xl text-sm"><b>{x.alumno}</b> · {x.curso} · {x.periodo}: {x.calificacion_anterior||'Sin nota'} → {x.calificacion_nueva}<br/><span className="text-cream-600">{x.usuario} · {new Date(x.fecha).toLocaleString()} · {x.motivo||'Registro inicial'}</span></div>)}</div></section>}
    {tab==='acom'&&<section className="bg-white p-5 rounded-2xl border space-y-4"><h2>Conducta, comentario del tutor y nota del padre</h2><select className="input-field" value={acom.alumno} onChange={e=>setAcom({...acom,alumno:e.target.value})}><option value="">Seleccione alumno</option>{gradebook?.alumnos.map(a=><option key={a.id} value={a.id}>{a.nombre_completo}</option>)}</select><div className="grid md:grid-cols-2 gap-3">{data?.criterios.map(c=><label key={c.id} className="flex justify-between items-center border rounded-xl p-3"><span>{c.nombre}</span><select value={acom.conducta[c.id]||''} onChange={e=>setAcom({...acom,conducta:{...acom.conducta,[c.id]:e.target.value}})}>{NOTAS.map(n=><option key={n}>{n||'—'}</option>)}</select></label>)}</div><select className="input-field" value={acom.tutor} onChange={e=>setAcom({...acom,tutor:e.target.value})}><option value="">Comentario del tutor</option>{commentsTutor.map(c=><option key={c.id} value={c.id}>{c.texto}</option>)}</select><select className="input-field" value={acom.padre} onChange={e=>setAcom({...acom,padre:e.target.value})}><option value="">Nota del padre</option>{notesParent.map(c=><option key={c.id} value={c.id}>{c.texto}</option>)}</select><button className="btn-primary" onClick={async()=>{try{await api.guardarAcompanamiento({id_alumno:Number(acom.alumno),id_periodo:Number(periodoId),conducta:Object.entries(acom.conducta).filter(([,v])=>v).map(([id,v])=>({id_criterio:Number(id),calificacion:v})),observaciones:[acom.tutor&&{tipo:'COMENTARIO_TUTOR',id_catalogo:Number(acom.tutor)},acom.padre&&{tipo:'NOTA_PADRE',id_catalogo:Number(acom.padre)}].filter(Boolean)});toast.success('Acompañamiento guardado');}catch(e){toast.error(errorText(e));}}}>Guardar acompañamiento</button></section>}
  </div>;
}
