import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { HiCheckCircle, HiDocumentText, HiExternalLink, HiLockClosed, HiPrinter, HiShieldCheck } from 'react-icons/hi';
import { aceptarMatriculaPublica, obtenerMatriculaPublica } from '../services/matriculasService';
import logo from '../assets/logo-harvard.png';

const money = (value) => `S/ ${Number(value || 0).toLocaleString('es-PE', { minimumFractionDigits: 2 })}`;
const input = 'w-full rounded-xl border border-stone-300 bg-white px-4 py-3 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100';

export default function MatriculaPublica() {
  const { token } = useParams();
  const [record, setRecord] = useState(null);
  const [error, setError] = useState('');
  const [sending, setSending] = useState(false);
  const [done, setDone] = useState(null);
  const [form, setForm] = useState({ celular: '', email: '', direccion: '', contacto_emergencia: '', telefono_emergencia: '', observaciones_salud: '', persona_autorizada_1: { nombre: '', dni: '', parentesco: '', celular: '' }, persona_autorizada_2: { nombre: '', dni: '', parentesco: '', celular: '' } });
  const [accept, setAccept] = useState({ declaracion: false });
  const [otp, setOtp] = useState('');
  useEffect(() => { obtenerMatriculaPublica(token).then(({ data }) => { const x = data.data; setRecord(x); setForm((old) => ({ ...old, ...x.formulario, celular: x.formulario?.celular || x.datos?.apoderado?.celular || '', persona_autorizada_1: { ...old.persona_autorizada_1, ...(x.formulario?.persona_autorizada_1 || {}) }, persona_autorizada_2: { ...old.persona_autorizada_2, ...(x.formulario?.persona_autorizada_2 || {}) } })); setAccept(x.aceptaciones || { declaracion: false }); if (['ACEPTADA','COMPLETADA'].includes(x.estado)) setDone({ codigo: x.codigo, estado: x.estado, aceptado_en: x.aceptado_en, hash_evidencia: x.hash_evidencia }); }).catch((e) => setError(e.response?.data?.error || 'No se pudo abrir la invitación')); }, [token]);
  const mandatoryReady = useMemo(() => record?.documentos?.filter((d) => d.obligatorio !== false).every((d) => accept[d.clave]) && accept.declaracion, [record, accept]);
  const total = Number(record?.deuda || 0) + Number(record?.matricula || 0);
  const submit = async (event) => { event.preventDefault(); setSending(true); setError(''); try { const response = await aceptarMatriculaPublica(token, { formulario: form, aceptaciones: accept, otp }); setDone(response.data.data); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch (e) { setError(e.response?.data?.error || 'No se pudo registrar la aceptación'); } finally { setSending(false); } };
  if (error && !record) return <Shell><div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-700"><b>No pudimos abrir la matrícula.</b><p className="mt-2">{error}</p></div></Shell>;
  if (!record) return <Shell><p className="text-center text-stone-500">Abriendo matrícula segura...</p></Shell>;
  if (done) return <Shell><div className="rounded-3xl border border-emerald-200 bg-white p-6 text-center shadow-sm md:p-10"><HiCheckCircle className="mx-auto h-16 w-16 text-emerald-600"/><h1 className="mt-3 font-serif text-3xl font-bold text-red-900">Aceptación registrada</h1><p className="mt-2 text-stone-600">La matrícula digital de <b>{record.datos.alumno.nombre}</b> fue aceptada correctamente.</p><div className="mx-auto mt-6 max-w-xl rounded-2xl bg-stone-50 p-5 text-left"><p><b>Constancia:</b> {done.codigo}</p><p><b>Fecha:</b> {new Date(done.aceptado_en).toLocaleString('es-PE')}</p><p className="mt-2 break-all text-xs"><b>Huella digital de evidencia:</b> {done.hash_evidencia}</p></div><button onClick={() => window.print()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-red-800 px-5 py-3 font-semibold text-white print:hidden"><HiPrinter/>Imprimir o guardar constancia</button></div></Shell>;

  return <Shell><form onSubmit={submit} className="space-y-5">
    <section className="rounded-3xl bg-gradient-to-br from-red-900 to-red-700 p-6 text-white shadow-lg"><p className="text-sm text-amber-200">Matrícula digital {record.anio}</p><h1 className="mt-1 font-serif text-3xl font-bold">{record.datos.alumno.nombre}</h1><p className="mt-2 text-red-100">{record.datos.alumno.codigo} · {record.datos.alumno.nivel} · {record.datos.alumno.grado} {record.datos.alumno.seccion}</p><div className="mt-5 flex items-center gap-2 text-sm text-red-100"><HiShieldCheck/>Enlace personal protegido y aceptación con código</div></section>
    {record.estado === 'OBSERVADA' && <div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-800"><b>El colegio dejó una observación:</b> {record.observacion_revision}</div>}
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-bold text-red-900">1. Verifique y complete los datos</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{[['celular','Celular del apoderado *','tel'],['email','Correo electrónico','email'],['direccion','Dirección actual *','text'],['contacto_emergencia','Contacto de emergencia *','text'],['telefono_emergencia','Teléfono de emergencia','tel']].map(([key,label,type]) => <label key={key} className="text-sm font-medium text-stone-700">{label}<input type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={`${input} mt-1`} /></label>)}<label className="text-sm font-medium text-stone-700 md:col-span-2">Alergias, condición médica u observaciones de salud<textarea value={form.observaciones_salud} onChange={(e) => setForm({ ...form, observaciones_salud: e.target.value })} className={`${input} mt-1 min-h-24`} /></label></div><div className="mt-6 border-t border-stone-200 pt-5"><h3 className="font-bold text-red-900">Ficha para emergencias o desastres</h3><p className="mt-1 text-sm text-stone-600">Registre quiénes están autorizados para recoger al estudiante. La primera persona es obligatoria.</p>{[1,2].map((number) => { const key = `persona_autorizada_${number}`; const person = form[key] || {}; const update = (property, value) => setForm({ ...form, [key]: { ...person, [property]: value } }); return <div key={key} className="mt-4 rounded-xl bg-stone-50 p-4"><p className="mb-3 font-semibold text-stone-700">Persona autorizada {number}{number === 1 ? ' *' : ' (opcional)'}</p><div className="grid gap-3 md:grid-cols-2"><input value={person.nombre || ''} onChange={(e) => update('nombre', e.target.value)} placeholder="Nombres y apellidos" className={input}/><input value={person.dni || ''} onChange={(e) => update('dni', e.target.value.replace(/\D/g,'').slice(0,12))} inputMode="numeric" placeholder="DNI o documento" className={input}/><input value={person.parentesco || ''} onChange={(e) => update('parentesco', e.target.value)} placeholder="Parentesco o relación" className={input}/><input value={person.celular || ''} onChange={(e) => update('celular', e.target.value)} inputMode="tel" placeholder="Celular" className={input}/></div></div>; })}</div></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-bold text-red-900">2. Revise los documentos oficiales</h2><p className="mt-1 text-sm text-stone-600">Estos son los documentos y versiones que quedarán registrados en la evidencia.</p>{record.documentos[0]?.enlace && <a href={record.documentos[0].enlace} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-3 font-semibold text-white"><HiExternalLink/>Abrir carpeta de documentos</a>}<div className="mt-4 space-y-3">{record.documentos.map((d) => <label key={d.clave} className="flex cursor-pointer items-start gap-3 rounded-xl border border-stone-200 p-4"><input type="checkbox" checked={!!accept[d.clave]} onChange={(e) => setAccept({ ...accept, [d.clave]: e.target.checked })} className="mt-1 h-5 w-5 accent-red-800"/><span><b>{d.nombre}</b><small className="block text-stone-500">Versión {d.version}{d.obligatorio === false ? ' · aceptación opcional' : ' · obligatorio'}</small></span></label>)}</div></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-bold text-red-900">3. Resumen económico informativo</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['Deuda registrada', record.deuda], ['Matrícula', record.matricula], ['Total referencial', total]].map(([label,value]) => <div key={label} className="rounded-xl bg-stone-50 p-4"><p className="text-xs text-stone-500">{label}</p><p className="mt-1 text-xl font-bold text-red-900">{money(value)}</p></div>)}</div><p className="mt-3 text-xs text-stone-500">Este resumen no registra un pago. El colegio confirmará los importes y condiciones que correspondan.</p></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-serif text-xl font-bold text-red-900">4. Aceptación electrónica</h2><label className="mt-4 flex cursor-pointer items-start gap-3 rounded-xl border-2 border-red-100 p-4"><input type="checkbox" checked={!!accept.declaracion} onChange={(e) => setAccept({ ...accept, declaracion: e.target.checked })} className="mt-1 h-5 w-5 accent-red-800"/><span>Declaro que los datos son verdaderos, que tuve acceso a los documentos indicados y que acepto las condiciones marcadas en este formulario.</span></label><label className="mt-4 block text-sm font-semibold text-stone-700">Código de 6 dígitos recibido por WhatsApp<input inputMode="numeric" maxLength="6" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" className={`${input} mt-1 text-center text-2xl tracking-[0.4em]`} /></label>{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={sending || otp.length !== 6 || !mandatoryReady} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-red-800 px-5 py-4 font-bold text-white disabled:bg-stone-300"><HiLockClosed/>{sending ? 'Registrando...' : 'Aceptar y registrar matrícula'}</button><p className="mt-3 text-center text-xs text-stone-500">Se guardarán fecha, hora, dirección IP, dispositivo, documentos aceptados y una huella SHA-256 de la evidencia.</p></section>
  </form></Shell>;
}

function Shell({ children }) { return <div className="min-h-screen bg-[#f8f3ed] px-4 py-6 text-stone-800 md:py-10"><header className="mx-auto mb-6 flex max-w-3xl items-center gap-3"><img src={logo} alt="Colegio Harvard" className="h-14 w-14 rounded-full"/><div><p className="font-serif text-xl font-bold text-red-900">Colegio Harvard</p><p className="text-xs text-stone-500">Proceso seguro de matrícula digital</p></div></header><main className="mx-auto max-w-3xl">{children}</main><footer className="mx-auto mt-8 max-w-3xl text-center text-xs text-stone-500">Colegio Harvard · La aceptación electrónica no requiere dibujar una firma ni usar huella dactilar.</footer></div>; }

