import { useCallback, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { HiCurrencyDollar, HiDownload, HiReceiptTax, HiTrendingUp } from 'react-icons/hi';
import { exportarReporteEconomicoInventario, obtenerReporteEconomicoInventario } from '../../services/inventarioService';

const hoy = () => new Date().toISOString().slice(0, 10);
const inicioMes = () => `${hoy().slice(0, 8)}01`;
const dinero = value => `S/ ${Number(value || 0).toLocaleString('es-PE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function ReporteEconomicoInventario({ productos }) {
  const [filtros, setFiltros] = useState({ desde: inicioMes(), hasta: hoy(), categoria: '', id_producto: '', medio_pago: '' });
  const [reporte, setReporte] = useState({ resumen: {}, por_medio: [], por_categoria: [], operaciones: [] });
  const [cargando, setCargando] = useState(false);
  const categorias = useMemo(() => [...new Set(productos.map(p => p.categoria))].sort(), [productos]);
  const parametros = useMemo(() => Object.fromEntries(Object.entries(filtros).filter(([, value]) => value)), [filtros]);
  const cargar = useCallback(async () => { setCargando(true); try { const { data } = await obtenerReporteEconomicoInventario(parametros); setReporte(data.data); } catch (error) { toast.error(error.response?.data?.error || 'No se pudo cargar el reporte'); } finally { setCargando(false); } }, [parametros]);
  useEffect(() => { cargar(); }, [cargar]);
  const cambiar = (campo, value) => setFiltros(actual => ({ ...actual, [campo]: value, ...(campo === 'categoria' ? { id_producto: '' } : {}) }));
  const exportar = async () => { try { const { data } = await exportarReporteEconomicoInventario(parametros); const url = URL.createObjectURL(data); const enlace = document.createElement('a'); enlace.href = url; enlace.download = `reporte-economico-inventario-${hoy()}.xlsx`; enlace.click(); URL.revokeObjectURL(url); } catch { toast.error('No se pudo exportar el reporte'); } };
  const tarjetas = [['Total vendido', reporte.resumen.ventas, 'text-blue-700'], ['Ingresos cobrados', reporte.resumen.ingresos, 'text-emerald-700'], ['Saldos pendientes', reporte.resumen.pendientes, 'text-amber-700'], ['Costo estimado', reporte.resumen.costos, 'text-violet-700'], ['Utilidad estimada', reporte.resumen.utilidad_estimada, 'text-primary-700']];

  return <div className="space-y-4">
    <section className="card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-primary-800">Reporte económico de inventario</h2><p className="text-sm text-primary-600">Independiente de pensiones y otros conceptos académicos.</p></div><button onClick={exportar} className="rounded-lg bg-emerald-600 px-4 py-2.5 font-semibold text-white"><HiDownload className="mr-1 inline"/>Exportar reporte</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input type="date" value={filtros.desde} onChange={e=>cambiar('desde',e.target.value)} className="input-field" title="Desde"/><input type="date" value={filtros.hasta} onChange={e=>cambiar('hasta',e.target.value)} className="input-field" title="Hasta"/><select value={filtros.categoria} onChange={e=>cambiar('categoria',e.target.value)} className="input-field"><option value="">Toda categoría</option>{categorias.map(x=><option key={x}>{x}</option>)}</select><select value={filtros.id_producto} onChange={e=>cambiar('id_producto',e.target.value)} className="input-field"><option value="">Todo producto</option>{productos.filter(p=>!filtros.categoria||p.categoria===filtros.categoria).map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select><select value={filtros.medio_pago} onChange={e=>cambiar('medio_pago',e.target.value)} className="input-field"><option value="">Todo medio de pago</option>{['EFECTIVO','YAPE','PLIN','TRANSFERENCIA','PENDIENTE'].map(x=><option key={x}>{x}</option>)}</select></div></section>
    {cargando ? <div className="card p-10 text-center">Calculando reporte...</div> : <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{tarjetas.map(([label,value,color],index)=><div key={label} className="card p-4"><div className="flex items-center gap-2"><span className={`rounded-lg bg-cream-100 p-2 ${color}`}>{index===4?<HiTrendingUp/>:index===2?<HiReceiptTax/>:<HiCurrencyDollar/>}</span><p className="text-xs text-primary-600">{label}</p></div><p className={`mt-2 text-xl font-bold ${color}`}>{dinero(value)}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><ResumenGrupo titulo="Ingresos cobrados por medio de pago" datos={reporte.por_medio.map(x=>[x.medio,x.monto])}/><ResumenGrupo titulo="Ventas por categoría" datos={reporte.por_categoria.map(x=>[x.categoria,x.total])}/></div><div className="card overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-cream-50 text-left"><tr><th className="p-3">Fecha / recibo</th><th className="p-3">Comprador</th><th className="p-3">Productos</th><th className="p-3">Medio</th><th className="p-3">Vendido</th><th className="p-3">Cobrado</th><th className="p-3">Pendiente</th><th className="p-3">Utilidad est.</th></tr></thead><tbody className="divide-y">{reporte.operaciones.map(v=><tr key={v.id}><td className="p-3">{new Date(v.fecha).toLocaleDateString('es-PE')}<small className="block">{v.codigo}</small></td><td className="p-3">{v.comprador_nombre||v.alumno?.nombre_completo||'Venta general'}</td><td className="p-3">{v.items.map(i=>`${i.variante.producto.nombre} ${i.variante.nombre} ×${i.cantidad}`).join(', ')}</td><td className="p-3">{v.medio_pago||'-'}</td><td className="p-3">{dinero(v.total_reporte)}</td><td className="p-3 font-semibold text-emerald-700">{dinero(v.pagado_reporte)}</td><td className="p-3 text-amber-700">{dinero(v.saldo_reporte)}</td><td className="p-3 font-semibold">{dinero(v.utilidad_reporte)}</td></tr>)}</tbody></table>{!reporte.operaciones.length&&<p className="p-8 text-center text-primary-500">No hay operaciones en el periodo seleccionado.</p>}</div></>}
  </div>;
}

const ResumenGrupo = ({ titulo, datos }) => <section className="card p-4"><h3 className="font-semibold text-primary-800">{titulo}</h3><div className="mt-3 space-y-2">{datos.map(([label,value])=><div key={label} className="flex justify-between border-b border-cream-100 pb-2 text-sm"><span>{label}</span><b>{dinero(value)}</b></div>)}{!datos.length&&<p className="text-sm text-primary-500">Sin información para mostrar.</p>}</div></section>;
